#!/bin/bash
git config --global user.email "game.master.habib@gmail.com"
sleep 2
git config --global user.name "GMhabib"
sleep 2
git init
sleep 2
git config --global safe.directory /data/data/com.termux/files/home/website_youtube/
sleep 2
 git add *
 sleep 2
 git commit -m "jika sudah clone install pkg install nodejs"
 sleep 2
 clear
 echo "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"
 sleep 10
 git remote add origin https://github.com/GMhabib/Termux_Youtube_Web.git && git branch -M main && git push -u origin main
